// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: dist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DistRequest) Reset() {
	*x = DistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistRequest) ProtoMessage() {}

func (x *DistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistRequest.ProtoReflect.Descriptor instead.
func (*DistRequest) Descriptor() ([]byte, []int) {
	return file_dist_proto_rawDescGZIP(), []int{0}
}

func (x *DistRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DistResponse) Reset() {
	*x = DistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistResponse) ProtoMessage() {}

func (x *DistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistResponse.ProtoReflect.Descriptor instead.
func (*DistResponse) Descriptor() ([]byte, []int) {
	return file_dist_proto_rawDescGZIP(), []int{1}
}

func (x *DistResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_dist_proto protoreflect.FileDescriptor

var file_dist_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x1d, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x3f, 0x5a, 0x3d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x72, 0x65, 0x62,
	0x65, 0x61, 0x72, 0x72, 0x65, 0x78, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2d, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x67,
	0x72, 0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dist_proto_rawDescOnce sync.Once
	file_dist_proto_rawDescData = file_dist_proto_rawDesc
)

func file_dist_proto_rawDescGZIP() []byte {
	file_dist_proto_rawDescOnce.Do(func() {
		file_dist_proto_rawDescData = protoimpl.X.CompressGZIP(file_dist_proto_rawDescData)
	})
	return file_dist_proto_rawDescData
}

var file_dist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dist_proto_goTypes = []interface{}{
	(*DistRequest)(nil),  // 0: graph_shortest_distance.DistRequest
	(*DistResponse)(nil), // 1: graph_shortest_distance.DistResponse
}
var file_dist_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dist_proto_init() }
func file_dist_proto_init() {
	if File_dist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dist_proto_goTypes,
		DependencyIndexes: file_dist_proto_depIdxs,
		MessageInfos:      file_dist_proto_msgTypes,
	}.Build()
	File_dist_proto = out.File
	file_dist_proto_rawDesc = nil
	file_dist_proto_goTypes = nil
	file_dist_proto_depIdxs = nil
}
